//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasvuruFormuSon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBasvurular
    {
        public int Id { get; set; }
        public string TCKimlikNo { get; set; }
        public string Adi { get; set; }
        public string Soyadi { get; set; }
        public string BabaAdi { get; set; }
        public string DogumTarihi { get; set; }
        public string Cinsiyet { get; set; }
        public string NufusKayitYer { get; set; }
        public string Fotograf { get; set; }
        public string MenzuniyetOkul { get; set; }
        public string MenzuniyetTarih { get; set; }
        public string Bolum { get; set; }
        public string TebligatAdres { get; set; }
        public string Ilce { get; set; }
        public string Il { get; set; }
        public string GSM { get; set; }
        public string SabitTel { get; set; }
        public string EpostaAdres { get; set; }
        public string PostaKodu { get; set; }
        public string MevcutKurum { get; set; }
        public string MevcutGorev { get; set; }
        public string EskiKurum { get; set; }
        public string EskiGorev { get; set; }
        public string AyrilisNedeni { get; set; }
        public string AyrilisTarihi { get; set; }
        public string AskerlikDurum { get; set; }
        public string AskerlikSekli { get; set; }
        public string AskerlikYapmadi { get; set; }
        public string MecburiHizmet { get; set; }
        public string YukumluKurum { get; set; }
        public string HizmetSuresi { get; set; }
        public string SicilKaydi { get; set; }
        public string SucSebebi { get; set; }
        public string CezaSuresi { get; set; }
        public string YetkiliAd { get; set; }
        public string YetkiliSoyad { get; set; }
        public string YetkiliGorev { get; set; }
        public string OnayTarih { get; set; }
    }
}
